// Editor JavaScript
const DEFAULT_CODING_API_BASE = localStorage.getItem('eti_lesson_api_base') || localStorage.getItem('eti_coding_api_base_default') || 'https://code.eti.com.hk';
const CODING_API_BASE = (localStorage.getItem('eti_coding_api_base') || DEFAULT_CODING_API_BASE).replace(/\/$/, '');

window.setCodingApiBase = function setCodingApiBase(baseUrl) {
    if (!baseUrl || !baseUrl.trim()) {
        console.warn('setCodingApiBase(baseUrl) requires a URL.');
        return;
    }
    localStorage.setItem('eti_coding_api_base', baseUrl.trim().replace(/\/$/, ''));
    console.info('Coding API base updated. Reloading editor...');
    window.location.reload();
};
window.setLessonApiBase = window.setCodingApiBase;

window.resetCodingApiBase = function resetCodingApiBase() {
    localStorage.removeItem('eti_coding_api_base');
    localStorage.removeItem('eti_lesson_api_base');
    console.info('Coding API base reset. Reloading editor...');
    window.location.reload();
};
window.resetLessonApiBase = window.resetCodingApiBase;

class LessonEditor {
    constructor() {
        this.lesson = {
            id: '',
            title: '',
            description: '',
            difficulty: 1,
            readingMaterial: [],
            questions: []
        };
        this.currentEditingBlock = null;
        this.currentEditingQuestion = null;
        this.textEditor = null;
        this.codeEditors = {};
        this.initialLessonSnapshot = '';
        this.draggedContentIndex = null;
        this.uploadedImageDataUrl = '';
        this.uploadedImageMeta = null;
        this.init();
    }

    init() {
        this.initializeQuill();
        this.setupEventListeners();
        this.setupCodeEditors();
        this.loadExistingLesson().catch((error) => {
            console.warn('Failed to load existing lesson from server/local storage:', error);
        });
        this.updatePreviewTitle();
        this.captureLessonSnapshot();
    }

    initializeQuill() {
        // Initialize Quill editor for text content
        this.textEditor = new Quill('#text-editor', {
            theme: 'snow',
            placeholder: 'Enter your text content here...',
            modules: {
                toolbar: [
                    ['bold', 'italic', 'underline', 'strike'],
                    ['blockquote', 'code-block'],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    [{ 'header': [1, 2, 3, false] }],
                    [{ 'color': [] }, { 'background': [] }],
                    ['clean']
                ]
            }
        });
    }

    setupCodeEditors() {
        // Initialize CodeMirror for code inputs
        const codeTextareas = document.querySelectorAll('textarea[id="code-content"], textarea[id$="-code"], textarea[id$="-precode"], textarea[id$="-solution"]');
        codeTextareas.forEach(textarea => {
            const editor = CodeMirror.fromTextArea(textarea, {
                lineNumbers: true,
                mode: 'javascript',
                theme: 'monokai',
                autoCloseBrackets: true,
                matchBrackets: true,
                indentUnit: 2,
                tabSize: 2,
                lineWrapping: true
            });
            this.codeEditors[textarea.id] = editor;
        });
    }

    setupEventListeners() {
        // Auto-generate lesson ID from title
        document.getElementById('lesson-title').addEventListener('input', (e) => {
            const title = e.target.value;
            const idField = document.getElementById('lesson-id');
            if (!idField.value || idField.dataset.autoGenerated) {
                idField.value = this.generateLessonId(title);
                idField.dataset.autoGenerated = 'true';
            }
        });

        // Mark ID as manually edited
        document.getElementById('lesson-id').addEventListener('input', (e) => {
            delete e.target.dataset.autoGenerated;
        });


        const imageDropzone = document.getElementById('image-upload-dropzone');
        const imageFileInput = document.getElementById('image-file-input');
        if (imageDropzone && imageFileInput) {
            ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
                imageDropzone.addEventListener(eventName, (e) => {
                    e.preventDefault();
                    e.stopPropagation();
                });
            });

            imageDropzone.addEventListener('dragover', () => {
                imageDropzone.classList.add('dragging');
            });
            imageDropzone.addEventListener('dragleave', () => {
                imageDropzone.classList.remove('dragging');
            });
            imageDropzone.addEventListener('drop', (e) => {
                imageDropzone.classList.remove('dragging');
                const file = e.dataTransfer?.files?.[0];
                if (file) {
                    this.handleImageFile(file);
                }
            });

            imageFileInput.addEventListener('change', (e) => {
                const file = e.target.files?.[0];
                if (file) {
                    this.handleImageFile(file);
                }
            });
        }

        const headingColorInput = document.getElementById('heading-color');
        if (headingColorInput) {
            headingColorInput.addEventListener('input', (e) => {
                this.updateHeadingColorDisplay(e.target.value);
            });
            this.updateHeadingColorDisplay(headingColorInput.value);
        }

        const tableHeaderBgInput = document.getElementById('table-header-bg');
        if (tableHeaderBgInput) {
            tableHeaderBgInput.addEventListener('input', (e) => {
                this.updateTableHeaderBgDisplay(e.target.value);
            });
            this.updateTableHeaderBgDisplay(tableHeaderBgInput.value);
        }

        // Close top-most modal with Escape
        document.addEventListener('keydown', (e) => {
            if (e.key !== 'Escape') {
                return;
            }
            const activeModals = document.querySelectorAll('.modal.active');
            if (activeModals.length > 0) {
                const topMostModal = activeModals[activeModals.length - 1];
                this.closeModal(topMostModal.id);
            }
        });
    }

    generateLessonId(title) {
        return title
            .toLowerCase()
            .replace(/[^a-z0-9\s-]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-')
            .trim() || 'stage-' + Date.now();
    }

    // Content Block Management
    addContentBlock(type) {
        this.currentEditingBlock = { type, index: null };
        this.openModal(`${type}-modal`);
    }

    saveTextBlock() {
        const content = this.textEditor.root.innerHTML;
        const text = this.textEditor.getText();
        
        const block = {
            type: 'text',
            text: text,
            html: content,
            style: { fontSize: '16px', lineHeight: '1.6' }
        };

        this.addOrUpdateContentBlock(block);
        this.closeModal('text-modal');
        this.textEditor.setText('');
    }

    saveHeadingBlock() {
        const text = document.getElementById('heading-text').value;
        const size = document.getElementById('heading-size').value;
        const color = document.getElementById('heading-color').value;

        if (!text.trim()) {
            this.showMessage('Please enter heading text', 'error');
            return;
        }

        const block = {
            type: 'heading',
            text: text,
            style: {
                fontSize: size,
                color: color,
                marginBottom: '16px'
            }
        };

        this.addOrUpdateContentBlock(block);
        this.closeModal('heading-modal');
        this.clearHeadingForm();
    }

    saveImageBlock() {
        const alignment = document.getElementById('image-alignment').value;
        const caption = document.getElementById('image-caption').value;
        const source = this.uploadedImageDataUrl;

        if (!source) {
            this.showMessage('Please upload an image', 'error');
            return;
        }

        const block = {
            type: 'image',
            src: source,
            alt: '',
            width: '100%',
            alignment: alignment,
            caption: caption || '',
            sourceType: 'upload',
            fileName: this.uploadedImageMeta?.name || ''
        };

        this.addOrUpdateContentBlock(block);
        this.closeModal('image-modal');
        this.clearImageForm();
    }

    saveTableBlock() {
        const headerInputs = document.querySelectorAll('#table-headers-container .table-header-input');
        const headers = Array.from(headerInputs).map((input, index) => input.value.trim() || `Column ${index + 1}`);
        const rows = document.querySelectorAll('#table-rows-container .table-row');

        if (headers.length === 0) {
            this.showMessage('Please add at least one column', 'error');
            return;
        }

        const tableData = {
            headers: headers,
            rows: [],
            style: {
                textAlign: document.getElementById('table-text-align').value,
                fontStyle: document.getElementById('table-font-style').value,
                fontWeight: document.getElementById('table-font-weight').value,
                headerBg: document.getElementById('table-header-bg').value,
                zebra: document.getElementById('table-zebra').checked,
                bordered: document.getElementById('table-bordered').checked
            }
        };

        rows.forEach(row => {
            const cells = row.querySelectorAll('.table-cell');
            const rowData = Array.from(cells).map(cell => cell.value.trim());
            if (rowData.some(cell => cell)) {
                tableData.rows.push(rowData);
            }
        });

        if (tableData.rows.length === 0) {
            this.showMessage('Please add at least one row with data', 'error');
            return;
        }

        const block = {
            type: 'table',
            ...tableData
        };

        this.addOrUpdateContentBlock(block);
        this.closeModal('table-modal');
        this.clearTableForm();
    }

    saveListBlock() {
        const type = document.getElementById('list-type').value === 'true';
        const items = document.querySelectorAll('#list-items-container .list-item-input');

        const listItems = Array.from(items)
            .map(input => input.value.trim())
            .filter(item => item);

        if (listItems.length === 0) {
            this.showMessage('Please add at least one list item', 'error');
            return;
        }

        const block = {
            type: 'list',
            ordered: type,
            items: listItems
        };

        this.addOrUpdateContentBlock(block);
        this.closeModal('list-modal');
        this.clearListForm();
    }

    saveCodeBlock() {
        const code = this.getInputValue('code-content');
        const language = document.getElementById('code-language').value;

        if (!code.trim()) {
            this.showMessage('Please enter code content', 'error');
            return;
        }

        const block = {
            type: 'code',
            code: code,
            language: language
        };

        this.addOrUpdateContentBlock(block);
        this.closeModal('code-modal');
        this.clearCodeForm();
    }

    addOrUpdateContentBlock(block) {
        if (this.currentEditingBlock.index !== null) {
            // Update existing block
            this.lesson.readingMaterial[this.currentEditingBlock.index] = block;
        } else {
            // Add new block
            this.lesson.readingMaterial.push(block);
        }
        this.renderContentBlocks();
    }

    renderContentBlocks() {
        const previewContainer = document.getElementById('learning-content-preview');
        const managementContainer = document.getElementById('content-blocks');
        
        if (this.lesson.readingMaterial.length === 0) {
            previewContainer.innerHTML = this.getContentEmptyStateMarkup();
            managementContainer.innerHTML = this.getContentManagerEmptyStateMarkup();
            return;
        }

        // Render in preview area (student view)
        previewContainer.innerHTML = this.renderJsonReadingMaterial(this.lesson.readingMaterial);

        // Render in management area (editor view)
        managementContainer.innerHTML = this.lesson.readingMaterial.map((block, index) => {
            const preview = this.getContentPreview(block);
            return `
                <div class="content-block" draggable="true"
                    ondragstart="lessonEditor.handleContentDragStart(event, ${index})"
                    ondragover="lessonEditor.handleContentDragOver(event)"
                    ondrop="lessonEditor.handleContentDrop(event, ${index})"
                    ondragend="lessonEditor.handleContentDragEnd(event)">
                    <div class="content-block-header">
                        <div class="content-block-meta">
                            <span class="drag-handle" title="Drag to reorder">
                                <i class="fas fa-grip-vertical"></i>
                            </span>
                            <span class="content-block-type">${this.getBlockTypeName(block.type)}</span>
                        </div>
                        <div class="content-block-actions">
                            <button class="content-block-btn" onclick="lessonEditor.editContentBlock(${index})">
                                <i class="fas fa-edit"></i> Edit
                            </button>
                            <button class="content-block-btn delete" onclick="lessonEditor.deleteContentBlock(${index})">
                                <i class="fas fa-trash"></i> Delete
                            </button>
                        </div>
                    </div>
                    <div class="content-block-preview">${preview}</div>
                </div>
            `;
        }).join('');
    }

    handleContentDragStart(event, index) {
        this.draggedContentIndex = index;
        event.dataTransfer.effectAllowed = 'move';
        event.dataTransfer.setData('text/plain', String(index));
        event.currentTarget.classList.add('dragging');
    }

    handleContentDragOver(event) {
        event.preventDefault();
        event.currentTarget.classList.add('drag-over');
    }

    handleContentDrop(event, dropIndex) {
        event.preventDefault();
        event.currentTarget.classList.remove('drag-over');

        if (this.draggedContentIndex === null || this.draggedContentIndex === dropIndex) {
            return;
        }

        const movedBlock = this.lesson.readingMaterial[this.draggedContentIndex];
        this.lesson.readingMaterial.splice(this.draggedContentIndex, 1);
        this.lesson.readingMaterial.splice(dropIndex, 0, movedBlock);

        this.draggedContentIndex = null;
        this.renderContentBlocks();
    }

    handleContentDragEnd(event) {
        this.draggedContentIndex = null;
        document.querySelectorAll('.content-block').forEach((block) => {
            block.classList.remove('dragging', 'drag-over');
        });
        if (event && event.currentTarget) {
            event.currentTarget.classList.remove('dragging');
        }
    }

    getContentPreview(block) {
        switch (block.type) {
            case 'text':
                return block.text ? block.text.substring(0, 100) + (block.text.length > 100 ? '...' : '') : 'No text content';
            case 'heading':
                return `<h3 style="color: #64ffda; font-size: ${block.style?.fontSize || '20px'}">${block.text}</h3>`;
            case 'image':
                return `<img src="${block.src}" alt="${block.alt}" style="max-width: 100px; height: auto; border-radius: 4px;"> ${block.alt || 'Image'}`;
            case 'table':
                const headerCount = block.headers?.length || 0;
                const rowCount = block.rows?.length || 0;
                return `Table: ${headerCount} columns, ${rowCount} rows`;
            case 'list':
                const itemCount = block.items?.length || 0;
                return `${block.ordered ? 'Ordered' : 'Unordered'} list: ${itemCount} items`;
            case 'code':
                return `<code style="background: #2c3e50; padding: 4px 8px; border-radius: 4px; color: #64ffda;">${block.language || 'code'}</code>`;
            default:
                return 'Unknown content type';
        }
    }

    getBlockTypeName(type) {
        const names = {
            text: 'Text',
            heading: 'Heading',
            image: 'Image',
            table: 'Table',
            list: 'List',
            code: 'Code'
        };
        return names[type] || type;
    }

    editContentBlock(index) {
        const block = this.lesson.readingMaterial[index];
        this.currentEditingBlock = { type: block.type, index };
        
        // Populate modal with existing data
        this.populateContentModal(block);
        this.openModal(`${block.type}-modal`);
    }

    populateContentModal(block) {
        switch (block.type) {
            case 'text':
                this.textEditor.root.innerHTML = block.html || '';
                break;
            case 'heading':
                document.getElementById('heading-text').value = block.text || '';
                document.getElementById('heading-size').value = block.style?.fontSize || '20px';
                document.getElementById('heading-color').value = block.style?.color || '#333333';
                this.updateHeadingColorDisplay(document.getElementById('heading-color').value);
                break;
            case 'image':
                this.uploadedImageDataUrl = block.src?.startsWith('data:image') ? block.src : '';
                this.uploadedImageMeta = this.uploadedImageDataUrl ? { name: block.fileName || 'uploaded-image' } : null;
                document.getElementById('image-alignment').value = block.alignment || 'center';
                document.getElementById('image-caption').value = block.caption || '';
                if (this.uploadedImageDataUrl) {
                    this.setImageUploadStatus(`Uploaded: ${block.fileName || 'image file'}`, 'success');
                } else {
                    this.setImageUploadStatus(block.src ? 'Using image URL source' : 'No file selected', 'info');
                }
                this.previewImage(block.src);
                break;
            case 'table':
                this.populateTableForm(block);
                break;
            case 'list':
                document.getElementById('list-type').value = block.ordered.toString();
                this.populateListItems(block.items || []);
                break;
            case 'code':
                this.setInputValue('code-content', block.code || '');
                document.getElementById('code-language').value = block.language || 'javascript';
                break;
        }
    }

    deleteContentBlock(index) {
        if (confirm('Are you sure you want to delete this content block?')) {
            this.lesson.readingMaterial.splice(index, 1);
            this.renderContentBlocks();
        }
    }

    // Question Management
    addQuestion(type) {
        this.currentEditingQuestion = { type, index: null };
        this.openModal(`${type}-modal`);
    }

    saveMCQQuestion() {
        const question = document.getElementById('mcq-question').value;
        const options = Array.from(document.querySelectorAll('.editor-option-text')).map(input => input.value.trim());
        const correctAnswer = document.querySelector('input[name="correct-answer"]:checked')?.value;
        const explanation = document.getElementById('mcq-explanation').value;

        if (!question.trim()) {
            this.showMessage('Please enter a question', 'error');
            return;
        }

        if (options.length < 2) {
            this.showMessage('Please add at least 2 options', 'error');
            return;
        }

        if (options.some(option => !option)) {
            this.showMessage('Please fill in all answer options', 'error');
            return;
        }

        if (correctAnswer === undefined) {
            this.showMessage('Please select the correct answer', 'error');
            return;
        }

        const questionData = {
            type: 'mcq',
            question: question,
            options: options,
            correctAnswer: parseInt(correctAnswer),
            explanation: explanation
        };

        this.addOrUpdateQuestion(questionData);
        this.closeModal('mcq-modal');
        this.clearMCQForm();
    }

    saveCodingQuestion() {
        const question = document.getElementById('coding-question').value;
        const precode = this.getInputValue('coding-precode');
        const solution = this.getInputValue('coding-solution');
        const explanation = document.getElementById('coding-explanation').value;

        if (!question.trim()) {
            this.showMessage('Please enter a question', 'error');
            return;
        }

        if (!solution.trim()) {
            this.showMessage('Please provide a solution', 'error');
            return;
        }

        const questionData = {
            type: 'coding',
            question: question,
            preCode: precode,
            solution: solution,
            explanation: explanation
        };

        this.addOrUpdateQuestion(questionData);
        this.closeModal('coding-modal');
        this.clearCodingForm();
    }

    addOrUpdateQuestion(questionData) {
        if (this.currentEditingQuestion.index !== null) {
            // Update existing question
            this.lesson.questions[this.currentEditingQuestion.index] = questionData;
        } else {
            // Add new question
            this.lesson.questions.push(questionData);
        }
        this.renderQuestions();
    }

    renderQuestions() {
        const container = document.getElementById('questions-container');
        
        if (this.lesson.questions.length === 0) {
            container.innerHTML = this.getQuestionsEmptyStateMarkup();
            return;
        }

        container.innerHTML = this.lesson.questions.map((question, index) => {
            return `
                <div class="question-block">
                    <div class="question-header">
                        <span class="question-type">${question.type === 'mcq' ? 'Multiple Choice' : 'Coding'}</span>
                        <div class="question-actions">
                            <button class="content-block-btn" onclick="lessonEditor.editQuestion(${index})">
                                <i class="fas fa-edit"></i> Edit
                            </button>
                            <button class="content-block-btn delete" onclick="lessonEditor.deleteQuestion(${index})">
                                <i class="fas fa-trash"></i> Delete
                            </button>
                        </div>
                    </div>
                    <div class="question-text">${this.escapeHtml(question.question).replace(/\n/g, '<br>')}</div>
                    ${this.renderQuestionPreview(question)}
                </div>
            `;
        }).join('');
    }

    renderQuestionPreview(question) {
        if (question.type === 'mcq') {
            const optionsHtml = question.options.map((option, index) => {
                const isCorrect = index === question.correctAnswer;
                return `<div class="question-option ${isCorrect ? 'correct' : ''}">${index + 1}. ${this.escapeHtml(option).replace(/\n/g, '<br>')}</div>`;
            }).join('');
            return `<div class="question-options">${optionsHtml}</div>`;
        } else {
            return `<div class="question-code">${question.preCode || '// Starter code'}</div>`;
        }
    }

    editQuestion(index) {
        const question = this.lesson.questions[index];
        this.currentEditingQuestion = { type: question.type, index };
        
        // Populate modal with existing data
        this.populateQuestionModal(question);
        this.openModal(`${question.type}-modal`);
    }

    populateQuestionModal(question) {
        if (question.type === 'mcq') {
            document.getElementById('mcq-question').value = question.question || '';
            document.getElementById('mcq-explanation').value = question.explanation || '';
            this.populateMCQOptions(question.options, question.correctAnswer);
        } else {
            document.getElementById('coding-question').value = question.question || '';
            this.setInputValue('coding-precode', question.preCode || '');
            this.setInputValue('coding-solution', question.solution || '');
            document.getElementById('coding-explanation').value = question.explanation || '';
        }
    }

    deleteQuestion(index) {
        if (confirm('Are you sure you want to delete this question?')) {
            this.lesson.questions.splice(index, 1);
            this.renderQuestions();
        }
    }

    // Form Management
    addTableColumn(headerText = '') {
        const headersContainer = document.getElementById('table-headers-container');
        const columnCount = headersContainer.querySelectorAll('.table-header-item').length;
        const newIndex = columnCount + 1;

        const headerItem = document.createElement('div');
        headerItem.className = 'table-header-item';
        headerItem.innerHTML = `
            <input type="text" placeholder="Header ${newIndex}" class="table-header-input" value="${this.escapeHtml(headerText)}">
            <button class="btn btn-danger table-header-remove" onclick="removeTableColumn(this)" title="Remove column">
                <i class="fas fa-minus"></i>
            </button>
        `;
        headersContainer.appendChild(headerItem);

        const rows = document.querySelectorAll('#table-rows-container .table-row-cells');
        rows.forEach((cellsContainer) => {
            const input = document.createElement('input');
            input.type = 'text';
            input.className = 'table-cell';
            input.placeholder = `Cell ${newIndex}`;
            cellsContainer.appendChild(input);
        });
    }

    removeTableColumn(button) {
        const headersContainer = document.getElementById('table-headers-container');
        const headerItems = headersContainer.querySelectorAll('.table-header-item');
        if (headerItems.length <= 1) {
            this.showMessage('A table must have at least one column', 'error');
            return;
        }

        const headerItem = button.closest('.table-header-item');
        const columnIndex = Array.from(headerItems).indexOf(headerItem);
        if (columnIndex < 0) {
            return;
        }

        headerItem.remove();
        const rows = document.querySelectorAll('#table-rows-container .table-row-cells');
        rows.forEach((cellsContainer) => {
            if (cellsContainer.children[columnIndex]) {
                cellsContainer.children[columnIndex].remove();
            }
        });

        this.renumberTablePlaceholders();
    }

    addTableRow(rowData = []) {
        const container = document.getElementById('table-rows-container');
        const row = this.createTableRowElement(rowData);
        container.appendChild(row);
    }

    removeTableRow(button) {
        const container = document.getElementById('table-rows-container');
        if (container.children.length <= 1) {
            this.showMessage('A table must have at least one row', 'error');
            return;
        }
        const row = button.closest('.table-row');
        row.remove();
    }

    addListItem() {
        const container = document.getElementById('list-items-container');
        const item = document.createElement('div');
        item.className = 'list-item';
        
        const input = document.createElement('input');
        input.type = 'text';
        input.className = 'list-item-input';
        input.placeholder = 'List item';
        
        const deleteBtn = document.createElement('button');
        deleteBtn.className = 'btn btn-danger';
        deleteBtn.innerHTML = '<i class="fas fa-trash"></i>';
        deleteBtn.onclick = () => removeListItem(deleteBtn);
        
        item.appendChild(input);
        item.appendChild(deleteBtn);
        container.appendChild(item);
    }

    removeListItem(button) {
        const item = button.parentElement;
        item.remove();
    }

    addMCQOption() {
        const container = document.getElementById('mcq-options-container');
        const optionCount = container.children.length;
        const option = this.createMCQOptionElement(optionCount);
        container.appendChild(option);
    }

    removeMCQOption(button) {
        const container = document.getElementById('mcq-options-container');
        if (container.children.length <= 2) {
            this.showMessage('Multiple choice questions need at least 2 options', 'error');
            return;
        }
        const option = button.parentElement;
        option.remove();
        // Update radio button values
        this.updateMCQRadioValues();
    }

    updateMCQRadioValues() {
        const options = document.querySelectorAll('#mcq-options-container .editor-mcq-option');
        options.forEach((option, index) => {
            const letter = option.querySelector('.option-letter');
            const input = option.querySelector('.editor-option-text');
            if (letter) {
                letter.textContent = this.getOptionLabel(index);
            }
            if (input) {
                input.placeholder = `Option ${this.getOptionLabel(index)}`;
            }
        });

        const radios = document.querySelectorAll('input[name="correct-answer"]');
        radios.forEach((radio, index) => {
            radio.value = index;
        });
    }

    // Modal Management
    openModal(modalId) {
        const modal = document.getElementById(modalId);
        modal.classList.add('active');
        document.body.style.overflow = 'hidden';
        this.refreshCodeEditors();
    }

    closeModal(modalId) {
        document.getElementById(modalId).classList.remove('active');
        if (document.querySelectorAll('.modal.active').length === 0) {
            document.body.style.overflow = '';
        }
    }

    // Form Clear Functions
    clearHeadingForm() {
        document.getElementById('heading-text').value = '';
        document.getElementById('heading-size').value = '20px';
        document.getElementById('heading-color').value = '#333333';
        this.updateHeadingColorDisplay('#333333');
    }

    clearImageForm() {
        document.getElementById('image-alignment').value = 'center';
        document.getElementById('image-caption').value = '';
        document.getElementById('image-file-input').value = '';
        this.uploadedImageDataUrl = '';
        this.uploadedImageMeta = null;
        this.setImageUploadStatus('No file selected', 'muted');
        document.getElementById('image-preview-img').style.display = 'none';
    }

    clearTableForm() {
        this.populateTableForm({
            headers: ['Header 1', 'Header 2', 'Header 3'],
            rows: [['', '', '']],
            style: {
                textAlign: 'left',
                fontStyle: 'normal',
                fontWeight: '400',
                headerBg: '#334466',
                zebra: true,
                bordered: true
            }
        });
    }

    clearListForm() {
        document.getElementById('list-type').value = 'false';
        const container = document.getElementById('list-items-container');
        container.innerHTML = `
            <div class="list-item">
                <input type="text" placeholder="List item 1" class="list-item-input">
                <button class="btn btn-danger" onclick="removeListItem(this)">
                    <i class="fas fa-trash"></i>
                </button>
            </div>
        `;
    }

    clearCodeForm() {
        this.setInputValue('code-content', '');
        document.getElementById('code-language').value = 'javascript';
    }

    clearMCQForm() {
        document.getElementById('mcq-question').value = '';
        document.getElementById('mcq-explanation').value = '';
        const container = document.getElementById('mcq-options-container');
        container.innerHTML = '';
        container.appendChild(this.createMCQOptionElement(0));
        container.appendChild(this.createMCQOptionElement(1));
    }

    clearCodingForm() {
        document.getElementById('coding-question').value = '';
        this.setInputValue('coding-precode', '');
        this.setInputValue('coding-solution', '');
        document.getElementById('coding-explanation').value = '';
    }

    // Helper Functions
    getInputValue(inputId) {
        if (this.codeEditors[inputId]) {
            return this.codeEditors[inputId].getValue();
        }
        const element = document.getElementById(inputId);
        return element ? element.value : '';
    }

    setImageUploadStatus(message, type = 'info') {
        const statusEl = document.getElementById('image-upload-status');
        if (!statusEl) {
            return;
        }
        statusEl.textContent = message;
        statusEl.className = `image-upload-status ${type}`;
    }

    async handleImageFile(file) {
        if (!file.type.startsWith('image/')) {
            this.showMessage('Please upload a valid image file', 'error');
            return;
        }

        const maxSizeBytes = 5 * 1024 * 1024;
        if (file.size > maxSizeBytes) {
            this.showMessage('Image is too large. Maximum size is 5MB.', 'error');
            return;
        }

        try {
            this.setImageUploadStatus('Processing image...', 'info');
            const originalDataUrl = await this.readFileAsDataUrl(file);
            const originalBytes = this.estimateDataUrlBytes(originalDataUrl);

            let finalDataUrl = originalDataUrl;
            let finalBytes = originalBytes;
            let compressionApplied = false;

            // Keep GIF as-is to avoid losing animation frames.
            if (file.type !== 'image/gif') {
                const compressed = await this.compressImageDataUrl(originalDataUrl, {
                    maxWidth: 1600,
                    maxHeight: 1600,
                    quality: 0.82
                });
                const compressedBytes = this.estimateDataUrlBytes(compressed);

                if (compressedBytes < originalBytes * 0.98) {
                    finalDataUrl = compressed;
                    finalBytes = compressedBytes;
                    compressionApplied = true;
                }
            }

            this.uploadedImageDataUrl = finalDataUrl;
            this.uploadedImageMeta = { name: file.name, size: finalBytes, type: 'image/data-url' };
            this.previewImage(this.uploadedImageDataUrl);

            if (compressionApplied) {
                const reduction = Math.round((1 - (finalBytes / originalBytes)) * 100);
                this.setImageUploadStatus(
                    `Uploaded ${file.name}: ${this.formatFileSize(originalBytes)} -> ${this.formatFileSize(finalBytes)} (${reduction}% smaller)`,
                    'success'
                );
            } else {
                this.setImageUploadStatus(`Uploaded ${file.name}: ${this.formatFileSize(finalBytes)}`, 'success');
            }
        } catch (error) {
            console.error('Image upload/compression error:', error);
            this.showMessage('Failed to process image file', 'error');
            this.setImageUploadStatus('Failed to process image file', 'error');
        }
    }

    formatFileSize(bytes) {
        if (bytes < 1024) {
            return `${bytes} B`;
        }
        if (bytes < 1024 * 1024) {
            return `${(bytes / 1024).toFixed(1)} KB`;
        }
        return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
    }

    estimateDataUrlBytes(dataUrl) {
        if (!dataUrl || typeof dataUrl !== 'string') {
            return 0;
        }
        const commaIndex = dataUrl.indexOf(',');
        if (commaIndex === -1) {
            return 0;
        }
        const base64 = dataUrl.slice(commaIndex + 1);
        const padding = (base64.match(/=+$/) || [''])[0].length;
        return Math.floor((base64.length * 3) / 4) - padding;
    }

    readFileAsDataUrl(file) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(reader.result);
            reader.onerror = () => reject(new Error('Failed to read file'));
            reader.readAsDataURL(file);
        });
    }

    loadImageElementFromDataUrl(dataUrl) {
        return new Promise((resolve, reject) => {
            const image = new Image();
            image.onload = () => resolve(image);
            image.onerror = () => reject(new Error('Failed to load image'));
            image.src = dataUrl;
        });
    }

    async compressImageDataUrl(dataUrl, options = {}) {
        const image = await this.loadImageElementFromDataUrl(dataUrl);
        const maxWidth = options.maxWidth || 1600;
        const maxHeight = options.maxHeight || 1600;
        const quality = options.quality || 0.82;

        const widthScale = maxWidth / image.width;
        const heightScale = maxHeight / image.height;
        const scale = Math.min(1, widthScale, heightScale);

        const targetWidth = Math.max(1, Math.round(image.width * scale));
        const targetHeight = Math.max(1, Math.round(image.height * scale));

        const canvas = document.createElement('canvas');
        canvas.width = targetWidth;
        canvas.height = targetHeight;

        const ctx = canvas.getContext('2d');
        ctx.imageSmoothingEnabled = true;
        ctx.imageSmoothingQuality = 'high';
        ctx.drawImage(image, 0, 0, targetWidth, targetHeight);

        // Prefer WEBP for better compression; fallback to JPEG when unavailable.
        let compressedDataUrl = canvas.toDataURL('image/webp', quality);
        if (!compressedDataUrl.startsWith('data:image/webp')) {
            compressedDataUrl = canvas.toDataURL('image/jpeg', quality);
        }

        return compressedDataUrl;
    }

    setInputValue(inputId, value) {
        if (this.codeEditors[inputId]) {
            this.codeEditors[inputId].setValue(value || '');
            return;
        }
        const element = document.getElementById(inputId);
        if (element) {
            element.value = value || '';
        }
    }

    updateHeadingColorDisplay(color) {
        const colorValue = document.getElementById('heading-color-value');
        const colorPreview = document.getElementById('heading-color-preview');
        if (colorValue) {
            colorValue.textContent = color;
        }
        if (colorPreview) {
            colorPreview.style.backgroundColor = color;
        }
    }

    updateTableHeaderBgDisplay(color) {
        const colorValue = document.getElementById('table-header-bg-value');
        const colorPreview = document.getElementById('table-header-bg-preview');
        if (colorValue) {
            colorValue.textContent = color;
        }
        if (colorPreview) {
            colorPreview.style.backgroundColor = color;
        }
    }

    renumberTablePlaceholders() {
        const headers = document.querySelectorAll('#table-headers-container .table-header-input');
        headers.forEach((header, index) => {
            if (!header.value.trim()) {
                header.placeholder = `Header ${index + 1}`;
            }
        });

        const rows = document.querySelectorAll('#table-rows-container .table-row-cells');
        rows.forEach((cellsContainer) => {
            Array.from(cellsContainer.children).forEach((cell, index) => {
                if (!cell.value.trim()) {
                    cell.placeholder = `Cell ${index + 1}`;
                }
            });
        });
    }

    createTableRowElement(rowData = []) {
        const headersCount = document.querySelectorAll('#table-headers-container .table-header-item').length || 1;
        const row = document.createElement('div');
        row.className = 'table-row';

        const cellsWrap = document.createElement('div');
        cellsWrap.className = 'table-row-cells';

        for (let i = 0; i < headersCount; i++) {
            const input = document.createElement('input');
            input.type = 'text';
            input.className = 'table-cell';
            input.placeholder = `Cell ${i + 1}`;
            input.value = rowData[i] || '';
            cellsWrap.appendChild(input);
        }

        const deleteBtn = document.createElement('button');
        deleteBtn.className = 'btn btn-danger';
        deleteBtn.innerHTML = '<i class="fas fa-trash"></i>';
        deleteBtn.onclick = () => removeTableRow(deleteBtn);

        row.appendChild(cellsWrap);
        row.appendChild(deleteBtn);
        return row;
    }

    refreshCodeEditors() {
        requestAnimationFrame(() => {
            Object.values(this.codeEditors).forEach((editor) => editor.refresh());
        });
    }

    getContentEmptyStateMarkup() {
        return `
            <div class="empty-state">
                <i class="fas fa-plus-circle"></i>
                <h3>No content yet</h3>
                <p>Click the buttons above to add your first content block and see it preview here</p>
            </div>
        `;
    }

    getContentManagerEmptyStateMarkup() {
        return `
            <div class="empty-state">
                <i class="fas fa-layer-group"></i>
                <h3>No blocks yet</h3>
                <p>Your content blocks will appear here when you add them.</p>
            </div>
        `;
    }

    getQuestionsEmptyStateMarkup() {
        return `
            <div class="empty-state">
                <i class="fas fa-question-circle"></i>
                <h3>No questions yet</h3>
                <p>Add questions to test student understanding</p>
            </div>
        `;
    }

    previewImage(url) {
        const preview = document.getElementById('image-preview-img');
        if (url) {
            preview.src = url;
            preview.style.display = 'block';
            preview.onerror = () => {
                preview.style.display = 'none';
            };
        } else {
            preview.style.display = 'none';
        }
    }

    populateTableForm(tableBlock) {
        const headers = Array.isArray(tableBlock.headers) && tableBlock.headers.length > 0 ? tableBlock.headers : ['Header 1'];
        const rows = Array.isArray(tableBlock.rows) && tableBlock.rows.length > 0 ? tableBlock.rows : [new Array(headers.length).fill('')];
        const style = tableBlock.style || {};

        const headersContainer = document.getElementById('table-headers-container');
        headersContainer.innerHTML = '';
        headers.forEach((headerText, index) => {
            const headerItem = document.createElement('div');
            headerItem.className = 'table-header-item';
            headerItem.innerHTML = `
                <input type="text" placeholder="Header ${index + 1}" class="table-header-input" value="${this.escapeHtml(headerText || '')}">
                <button class="btn btn-danger table-header-remove" onclick="removeTableColumn(this)" title="Remove column">
                    <i class="fas fa-minus"></i>
                </button>
            `;
            headersContainer.appendChild(headerItem);
        });

        const rowsContainer = document.getElementById('table-rows-container');
        rowsContainer.innerHTML = '';
        rows.forEach((rowData) => {
            rowsContainer.appendChild(this.createTableRowElement(rowData));
        });

        document.getElementById('table-text-align').value = style.textAlign || 'left';
        document.getElementById('table-font-style').value = style.fontStyle || 'normal';
        document.getElementById('table-font-weight').value = style.fontWeight || '400';
        const headerBg = style.headerBg || '#334466';
        document.getElementById('table-header-bg').value = headerBg;
        this.updateTableHeaderBgDisplay(headerBg);
        document.getElementById('table-zebra').checked = style.zebra !== false;
        document.getElementById('table-bordered').checked = style.bordered !== false;

        this.renumberTablePlaceholders();
    }

    populateListItems(items) {
        const container = document.getElementById('list-items-container');
        container.innerHTML = '';
        
        items.forEach(item => {
            const listItem = document.createElement('div');
            listItem.className = 'list-item';
            
            const input = document.createElement('input');
            input.type = 'text';
            input.className = 'list-item-input';
            input.value = item;
            
            const deleteBtn = document.createElement('button');
            deleteBtn.className = 'btn btn-danger';
            deleteBtn.innerHTML = '<i class="fas fa-trash"></i>';
            deleteBtn.onclick = () => removeListItem(deleteBtn);
            
            listItem.appendChild(input);
            listItem.appendChild(deleteBtn);
            container.appendChild(listItem);
        });
        
        // Add one empty item if no items
        if (items.length === 0) {
            this.addListItem();
        }
    }

    populateMCQOptions(options, correctAnswer) {
        const container = document.getElementById('mcq-options-container');
        container.innerHTML = '';
        
        options.forEach((option, index) => {
            container.appendChild(this.createMCQOptionElement(index, option, index === correctAnswer));
        });

        this.updateMCQRadioValues();
    }

    getOptionLabel(index) {
        if (index < 26) {
            return String.fromCharCode(65 + index);
        }
        return `#${index + 1}`;
    }

    createMCQOptionElement(index, optionText = '', isCorrect = false) {
        const option = document.createElement('div');
        option.className = 'editor-mcq-option';

        const correctToggle = document.createElement('label');
        correctToggle.className = 'correct-toggle';
        correctToggle.title = 'Mark this option as correct';

        const radio = document.createElement('input');
        radio.type = 'radio';
        radio.name = 'correct-answer';
        radio.value = index;
        radio.className = 'correct-answer-radio';
        radio.checked = isCorrect;

        correctToggle.appendChild(radio);

        const inputWrap = document.createElement('div');
        inputWrap.className = 'option-input-wrap';

        const optionLetter = document.createElement('span');
        optionLetter.className = 'option-letter';
        optionLetter.textContent = this.getOptionLabel(index);

        const input = document.createElement('input');
        input.type = 'text';
        input.className = 'editor-option-text';
        input.placeholder = `Option ${this.getOptionLabel(index)}`;
        input.value = optionText || '';

        inputWrap.appendChild(optionLetter);
        inputWrap.appendChild(input);

        const deleteBtn = document.createElement('button');
        deleteBtn.className = 'btn btn-danger option-delete-btn';
        deleteBtn.innerHTML = '<i class="fas fa-trash"></i>';
        deleteBtn.title = 'Delete option';
        deleteBtn.onclick = () => removeMCQOption(deleteBtn);

        option.appendChild(correctToggle);
        option.appendChild(inputWrap);
        option.appendChild(deleteBtn);
        return option;
    }

    // Save and Load Functions
    async saveLesson() {
        this.collectLessonData();
        
        if (!this.validateLesson()) {
            return;
        }

        const lessonData = {
            ...this.lesson,
            createdAt: new Date().toISOString()
        };

        this.saveLessonToStorage(lessonData);
        const serverSaved = await this.saveLessonToServer(lessonData);
        this.captureLessonSnapshot();
        if (serverSaved) {
            this.showMessage('Lesson saved to server and local draft successfully!', 'success');
        } else {
            this.showMessage('Lesson saved locally. Server sync was skipped or failed.', 'info');
        }
    }

    async clearAllLessons() {
        if (!confirm('DANGER: This will permanently delete ALL lessons from the server database. This action cannot be undone. Are you absolutely sure?')) {
            return;
        }

        const token = localStorage.getItem('eti_jwt_token');
        if (!token) {
            this.showMessage('No session found. Please login again.', 'error');
            return;
        }

        try {
            const response = await fetch(`${CODING_API_BASE}/api/lesson-content/all`, {
                method: 'DELETE',
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });

            if (response.ok) {
                this.showMessage('All lessons have been cleared from the server.', 'success');
                // Optional: Clear local storage too to match
                localStorage.removeItem('editorLessons');
                localStorage.removeItem('stagesIndex');
                
                // Reload after a short delay to refresh the UI
                setTimeout(() => {
                    window.location.reload();
                }, 1500);
            } else {
                const errorData = await response.json();
                this.showMessage(`Failed to clear lessons: ${errorData.error || 'Unknown error'}`, 'error');
            }
        } catch (error) {
            console.error('Clear all error:', error);
            this.showMessage('Network error while trying to clear lessons.', 'error');
        }
    }

    collectLessonData() {
        this.lesson.id = document.getElementById('lesson-id').value;
        this.lesson.title = document.getElementById('lesson-title').value;
        this.lesson.description = document.getElementById('lesson-description')?.value || '';
        this.lesson.difficulty = parseInt(document.getElementById('lesson-difficulty').value);
    }

    validateLesson() {
        if (!this.lesson.id.trim()) {
            this.showMessage('Please enter a lesson ID', 'error');
            return false;
        }

        if (!this.lesson.title.trim()) {
            this.showMessage('Please enter a lesson title', 'error');
            return false;
        }

        if (this.lesson.readingMaterial.length === 0) {
            this.showMessage('Please add at least one content block', 'error');
            return false;
        }

        if (this.lesson.questions.length === 0) {
            this.showMessage('Please add at least one question', 'error');
            return false;
        }

        return true;
    }

    saveLessonToStorage(lessonData) {
        // Save to localStorage for development
        const lessons = JSON.parse(localStorage.getItem('editorLessons') || '{}');
        lessons[lessonData.id] = lessonData;
        localStorage.setItem('editorLessons', JSON.stringify(lessons));

        // Also update stages index
        this.updateStagesIndex(lessonData);
    }

    async saveLessonToServer(lessonData) {
        const token = localStorage.getItem('eti_jwt_token');
        if (!token) {
            return false;
        }

        try {
            const response = await fetch(`${CODING_API_BASE}/api/lesson-content`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ lesson: lessonData })
            });

            if (!response.ok) {
                console.warn('Server save failed:', response.status, await response.text());
                return false;
            }
            return true;
        } catch (error) {
            console.warn('Server save error:', error);
            return false;
        }
    }

    updateStagesIndex(lessonData) {
        const indexData = JSON.parse(localStorage.getItem('stagesIndex') || '{"stages": []}');
        
        const existingStage = indexData.stages.find(s => s.id === lessonData.id);
        if (existingStage) {
            existingStage.title = lessonData.title;
            existingStage.description = lessonData.description;
            existingStage.lastUpdated = new Date().toISOString();
        } else {
            indexData.stages.push({
                id: lessonData.id,
                title: lessonData.title,
                description: lessonData.description,
                createdAt: lessonData.createdAt
            });
        }
        
        indexData.lastUpdated = new Date().toISOString();
        localStorage.setItem('stagesIndex', JSON.stringify(indexData));
    }

    async loadExistingLesson() {
        // Check if we're editing an existing lesson (from URL parameter)
        const urlParams = new URLSearchParams(window.location.search);
        const lessonId = urlParams.get('edit');
        
        if (!lessonId) {
            return;
        }

        let lesson = await this.loadLessonFromServer(lessonId);

        if (!lesson) {
            const lessons = JSON.parse(localStorage.getItem('editorLessons') || '{}');
            lesson = lessons[lessonId];
        }
        
        if (lesson) {
            this.lesson = lesson;
            this.populateLessonForm();
            this.renderContentBlocks();
            this.renderQuestions();
        }
    }

    async loadLessonById() {
        const lessonId = document.getElementById('lesson-id').value.trim();
        if (!lessonId) {
            this.showMessage('Please enter a lesson ID to load.', 'error');
            return;
        }

        let lesson = await this.loadLessonFromServer(lessonId);

        if (!lesson) {
            const lessons = JSON.parse(localStorage.getItem('editorLessons') || '{}');
            lesson = lessons[lessonId];
        }

        if (!lesson) {
            this.showMessage(`Lesson "${lessonId}" not found.`, 'error');
            return;
        }

        this.lesson = lesson;
        this.populateLessonForm();
        this.updatePreviewTitle();
        this.renderContentBlocks();
        this.renderQuestions();
        this.showMessage(`Loaded lesson "${lessonId}".`, 'success');
    }

    async loadLessonFromServer(lessonId) {
        const token = localStorage.getItem('eti_jwt_token');
        if (!token) {
            return null;
        }

        try {
            const response = await fetch(`${CODING_API_BASE}/api/lesson-content`, {
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });

            if (!response.ok) {
                return null;
            }

            const data = await response.json();
            const lessons = Array.isArray(data.lessons) ? data.lessons : [];
            return lessons.find((lesson) => lesson.id === lessonId) || null;
        } catch (error) {
            console.warn('Server load error:', error);
            return null;
        }
    }

    populateLessonForm() {
        document.getElementById('lesson-id').value = this.lesson.id;
        document.getElementById('lesson-title').value = this.lesson.title;
        const descriptionField = document.getElementById('lesson-description');
        if (descriptionField) {
            descriptionField.value = this.lesson.description;
        }
        document.getElementById('lesson-difficulty').value = this.lesson.difficulty;
    }

    previewLesson() {
        this.collectLessonData();
        
        if (!this.validateLesson()) {
            return;
        }

        // Save to localStorage and open preview
        const previewData = {
            ...this.lesson,
            isPreview: true
        };
        
        localStorage.setItem('previewLesson', JSON.stringify(previewData));
        
        // Open preview in new window
        const previewWindow = window.open('index.html?preview=true', '_blank');
        if (!previewWindow) {
            this.showMessage('Please allow popups to preview the lesson', 'error');
        }
    }

    showMessage(message, type = 'info') {
        // Create a temporary message element
        const messageEl = document.createElement('div');
        messageEl.className = `message ${type}`;
        messageEl.innerHTML = `
            <i class="fas fa-${type === 'success' ? 'check-circle' : type === 'error' ? 'exclamation-circle' : 'info-circle'}"></i>
            ${message}
        `;
        
        // Insert at the top of the editor main
        const editorMain = document.querySelector('.editor-main');
        editorMain.insertBefore(messageEl, editorMain.firstChild);
        
        // Remove after 3 seconds
        setTimeout(() => {
            messageEl.remove();
        }, 3000);
    }

    // Navigation
    goToMainSite() {
        if (this.hasUnsavedChanges()) {
            if (!confirm('You have unsaved changes. Are you sure you want to leave?')) {
                return;
            }
        }
        window.location.href = '../index.html';
    }

    hasUnsavedChanges() {
        this.collectLessonData();
        return JSON.stringify(this.lesson) !== this.initialLessonSnapshot;
    }

    captureLessonSnapshot() {
        this.collectLessonData();
        this.initialLessonSnapshot = JSON.stringify(this.lesson);
    }

    // Preview Methods
    updatePreviewTitle() {
        const titleInput = document.getElementById('lesson-title');
        const previewTitle = document.getElementById('preview-stage-title');

        if (!titleInput || !previewTitle) {
            return;
        }

        // Update immediately based on current lesson title
        previewTitle.textContent = titleInput.value.trim() || 'Stage Title Preview';

        // Keep in sync for future live edits
        titleInput.removeEventListener('input', this._previewTitleListener);
        this._previewTitleListener = () => {
            previewTitle.textContent = titleInput.value.trim() || 'Stage Title Preview';
        };
        titleInput.addEventListener('input', this._previewTitleListener);
    }

    renderJsonReadingMaterial(readingMaterial) {
        if (!Array.isArray(readingMaterial) || readingMaterial.length === 0) {
            return '<p>No reading material available.</p>';
        }

        return readingMaterial.map(item => {
            switch (item.type) {
                case 'text':
                    return `<p style="${this.renderStyle(item.style)}">${item.text}</p>`;
                case 'heading':
                    return `<h3 style="${this.renderStyle(item.style)}">${item.text}</h3>`;
                case 'image':
                    return `
                        <div style="text-align: ${item.alignment || 'center'}; margin: 1.5rem 0;">
                            <img src="${item.src}" alt="${item.alt || ''}" 
                                 style="max-width: ${item.width || '100%'}; height: auto; border-radius: 8px;">
                            ${item.caption ? `<p style="font-style: italic; color: #666; margin-top: 0.5rem;">${item.caption}</p>` : ''}
                        </div>
                    `;
                case 'table':
                    return this.renderJsonTable(item);
                case 'list':
                    return this.renderJsonList(item);
                case 'code':
                    return `
                        <pre style="background: #2c3e50; color: #ecf0f1; padding: 1.5rem; border-radius: 8px; overflow-x: auto; margin: 1rem 0;">
                            <code>${this.escapeHtml(item.code || item.text || '')}</code>
                        </pre>
                    `;
                default:
                    return `<p>Unknown content type: ${item.type}</p>`;
            }
        }).join('');
    }

    renderStyle(style) {
        if (!style) return '';
        return Object.entries(style).map(([key, value]) => 
            `${key.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${value}`
        ).join('; ');
    }

    renderJsonTable(tableData) {
        if (!tableData.headers || !tableData.rows) {
            return '<p>Invalid table data</p>';
        }

        const style = tableData.style || {};
        const textAlign = style.textAlign || 'left';
        const fontStyle = style.fontStyle || 'normal';
        const fontWeight = style.fontWeight || '400';
        const headerBg = style.headerBg || '#334466';
        const zebra = style.zebra !== false;
        const bordered = style.bordered !== false;
        const borderStyle = bordered ? '1px solid rgba(255, 255, 255, 0.16)' : 'none';

        const headers = tableData.headers.map(header => `
            <th style="padding: 10px 12px; text-align: ${textAlign}; border: ${borderStyle}; color: #ffffff; background: ${headerBg}; font-style: ${fontStyle}; font-weight: ${fontWeight};">
                ${this.escapeHtml(header)}
            </th>
        `).join('');

        const rows = tableData.rows.map((row, rowIndex) => {
            const cells = Array.isArray(row) ? row : [row];
            const rowBg = zebra && rowIndex % 2 === 1 ? 'rgba(255, 255, 255, 0.03)' : 'transparent';
            return `<tr style="background: ${rowBg};">${cells.map(cell => `
                <td style="padding: 10px 12px; text-align: ${textAlign}; border: ${borderStyle}; color: rgba(255, 255, 255, 0.9); font-style: ${fontStyle}; font-weight: ${fontWeight};">
                    ${this.escapeHtml(String(cell))}
                </td>
            `).join('')}</tr>`;
        }).join('');

        return `
            <table style="width: 100%; border-collapse: collapse; margin: 1.5rem 0; background: rgba(255,255,255,0.05); border-radius: 8px; overflow: hidden; border: ${borderStyle};">
                <thead><tr>${headers}</tr></thead>
                <tbody>${rows}</tbody>
            </table>
        `;
    }

    renderJsonList(listData) {
        if (!listData.items) {
            return '<p>Invalid list data</p>';
        }

        const tag = listData.ordered ? 'ol' : 'ul';
        const items = listData.items.map(item => `<li>${item}</li>`).join('');

        return `<${tag} style="margin: 1rem 0 1rem 2rem;">${items}</${tag}>`;
    }

    escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }
}

// Initialize the editor singleton
window.lessonEditor = new LessonEditor();

// Global handles for HTML onclick - explicitly attached to window
window.addContentBlock = (type) => window.lessonEditor.addContentBlock(type);
window.addQuestion = (type) => window.lessonEditor.addQuestion(type);
window.closeModal = (modalId) => window.lessonEditor.closeModal(modalId);
window.saveTextBlock = () => window.lessonEditor.saveTextBlock();
window.saveHeadingBlock = () => window.lessonEditor.saveHeadingBlock();
window.saveImageBlock = () => window.lessonEditor.saveImageBlock();
window.saveTableBlock = () => window.lessonEditor.saveTableBlock();
window.saveListBlock = () => window.lessonEditor.saveListBlock();
window.saveCodeBlock = () => window.lessonEditor.saveCodeBlock();
window.saveMCQQuestion = () => window.lessonEditor.saveMCQQuestion();
window.saveCodingQuestion = () => window.lessonEditor.saveCodingQuestion();
window.addTableRow = () => window.lessonEditor.addTableRow();
window.removeTableRow = (btn) => window.lessonEditor.removeTableRow(btn);
window.addTableColumn = () => window.lessonEditor.addTableColumn();
window.removeTableColumn = (btn) => window.lessonEditor.removeTableColumn(btn);
window.addListItem = () => window.lessonEditor.addListItem();
window.removeListItem = (btn) => window.lessonEditor.removeListItem(btn);
window.addMCQOption = () => window.lessonEditor.addMCQOption();
window.removeMCQOption = (btn) => window.lessonEditor.removeMCQOption(btn);
window.saveLesson = () => window.lessonEditor.saveLesson();
window.loadLessonById = () => window.lessonEditor.loadLessonById();
window.previewLesson = () => window.lessonEditor.previewLesson();
window.goToMainSite = () => window.lessonEditor.goToMainSite();
window.clearAllLessons = () => window.lessonEditor.clearAllLessons();
